import {
  ChecklistItem,
  OSState,
} from "@/types/os";

const now = new Date().toISOString();

const preReleaseLabels = [
  "final master complete",
  "cover art complete",
  "metadata complete",
  "uploaded to distributor",
  "Spotify pitch complete",
  "pre-save link ready",
  "visualizer/canvas ready",
  "teaser clips selected",
  "caption ideas written",
  "announcement post planned",
  "playlist pitching started",
];

const releaseDayLabels = [
  "main post published",
  "stories posted",
  "bio/links updated",
  "friends/fans messaged",
  "comments engaged with",
  "post pinned",
  "performance checked once",
];

const postReleaseLabels = [
  "repurpose clips",
  "behind-the-song post",
  "lyric content",
  "performance content",
  "acoustic/live version idea",
  "remix/DJ angle",
  "weekly analytics review",
  "learnings documented",
];

function checklist(labels: string[], doneCount = 0): ChecklistItem[] {
  return labels.map((label, i) => ({
    id: `${label}-${i}`.replace(/\s+/g, "-"),
    label,
    done: i < doneCount,
  }));
}

export function buildSeedData(): OSState {
  const songIdJune = "song-june-26";
  const songIdReleased = "song-midnight-drive";

  return {
    songs: [
      {
        id: songIdJune,
        title: "June 26",
        stage: "Mastering",
        priority: "High",
        vibe: "uplifting, bittersweet",
        theme: "moving on while still caring",
        genre: "house / pop",
        bpm: 124,
        key: "A minor",
        collaborators: "Jay (vocals)",
        producer: "6am",
        nextAction: "Approve final master",
        releasePotential: "High",
        notes: "Lead single for the June 26 rollout.",
        fileLinks: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: songIdReleased,
        title: "Midnight Drive",
        stage: "Released",
        priority: "Medium",
        vibe: "nighttime, reflective",
        theme: "driving alone after a breakup",
        genre: "house",
        bpm: 122,
        key: "G minor",
        collaborators: "",
        producer: "6am",
        nextAction: "Repurpose clips for content",
        releasePotential: "Medium",
        notes: "Released last month, steady streams.",
        fileLinks: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-idea-1",
        title: "Untitled Piano Idea",
        stage: "Idea",
        priority: "Medium",
        vibe: "intimate, raw",
        theme: "early morning clarity",
        genre: "house / piano",
        bpm: null,
        key: "",
        collaborators: "",
        producer: "",
        nextAction: "Build out a full demo",
        releasePotential: "Medium",
        notes: "Voice memo from last week, has a good hook.",
        fileLinks: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-idea-2",
        title: "Resilience",
        stage: "Demo",
        priority: "Low",
        vibe: "anthemic, hopeful",
        theme: "ambition after failure",
        genre: "house / pop",
        bpm: 126,
        key: "C major",
        collaborators: "",
        producer: "6am",
        nextAction: "Write second verse",
        releasePotential: "Medium",
        notes: "",
        fileLinks: "",
        createdAt: now,
        updatedAt: now,
      },
    ],
    releases: [
      {
        id: "release-june-26",
        title: "June 26 Release",
        linkedSongId: songIdJune,
        releaseDate: "2026-06-26",
        phase: "Pre-release",
        progress: 45,
        notes: "Lead single. Focus rollout for the next 2 weeks.",
        preReleaseChecklist: checklist(preReleaseLabels, 4),
        releaseDayChecklist: checklist(releaseDayLabels, 0),
        postReleaseChecklist: checklist(postReleaseLabels, 0),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "release-midnight-drive",
        title: "Midnight Drive",
        linkedSongId: songIdReleased,
        releaseDate: "2026-05-10",
        phase: "Post-release",
        progress: 100,
        notes: "Already out. Repurposing content from this.",
        preReleaseChecklist: checklist(preReleaseLabels, preReleaseLabels.length),
        releaseDayChecklist: checklist(releaseDayLabels, releaseDayLabels.length),
        postReleaseChecklist: checklist(postReleaseLabels, 2),
        createdAt: now,
        updatedAt: now,
      },
    ],
    content: [
      {
        id: "content-1",
        title: "POV: you finally let go of someone",
        platform: "TikTok",
        linkedSongId: songIdJune,
        format: "lyric meaning",
        status: "Idea",
        caption: "POV: you finally let go of someone who never deserved your loyalty",
        filmingNotes: "Shoot at golden hour, simple direct-to-camera setup.",
        postDate: "",
        metrics: { views: 0, likes: 0, comments: 0, shares: 0, saves: 0 },
        learning: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "content-2",
        title: "Studio session teaser",
        platform: "Instagram",
        linkedSongId: songIdJune,
        format: "studio clip",
        status: "Scripted",
        caption: "a small piece of June 26 🎹",
        filmingNotes: "Capture hands on keys + headphones, moody lighting.",
        postDate: "",
        metrics: { views: 0, likes: 0, comments: 0, shares: 0, saves: 0 },
        learning: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "content-3",
        title: "Midnight Drive piano version",
        platform: "YouTube Shorts",
        linkedSongId: songIdReleased,
        format: "piano version",
        status: "Posted",
        caption: "stripped back version of Midnight Drive",
        filmingNotes: "",
        postDate: "2026-05-20",
        metrics: { views: 4200, likes: 380, comments: 22, shares: 14, saves: 60 },
        learning: "Stripped down versions seem to perform better than full mixes.",
        createdAt: now,
        updatedAt: now,
      },
    ],
    vault: [
      {
        id: "vault-1",
        category: "Lyric idea",
        text: "\"I left the porch light on for someone who isn't coming back\"",
        mood: "bittersweet",
        linkedSongId: null,
        priority: "Medium",
        status: "Raw",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "vault-2",
        category: "Visual idea",
        text: "Cover art concept: empty highway at sunrise, neon reflections on wet road",
        mood: "nighttime / reflective",
        linkedSongId: songIdJune,
        priority: "High",
        status: "Useful",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "vault-3",
        category: "Rollout idea",
        text: "Countdown series: 5 days of behind-the-scenes clips before June 26 drops",
        mood: "energetic",
        linkedSongId: songIdJune,
        priority: "High",
        status: "Raw",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "vault-4",
        category: "Song title",
        text: "\"Echoes On Repeat\"",
        mood: "introspective",
        linkedSongId: null,
        priority: "Low",
        status: "Raw",
        createdAt: now,
        updatedAt: now,
      },
    ],
    brand: [
      {
        id: "brand-identity",
        section: "Identity",
        title: "Artist Identity",
        content:
          "Core message: emotional dance music for people processing real feelings.\nTarget listener: 18-30, late-night listener, going through something but still wants to move.\nEmotional world: heartbreak, resilience, ambition, emotional release.\nSonic lane: house-inspired, piano-driven, emotional.\nVisual lane: nighttime city, neon, intimate close-ups.\nWhat 6am is: honest, melodic, danceable but emotional.\nWhat 6am is not: generic EDM drops, try-hard hype, overly polished corporate pop.",
        updatedAt: now,
      },
      {
        id: "brand-sound",
        section: "Sound Direction",
        title: "Sound Direction",
        content:
          "- house-inspired sound\n- emotional dance music\n- uplifting production\n- introspective lyrics\n- piano influence\n- bittersweet but energetic\n- heartbreak, resilience, ambition, emotional release\n- nighttime / club / reflective energy",
        updatedAt: now,
      },
      {
        id: "brand-visual",
        section: "Visual Direction",
        title: "Visual Direction",
        content:
          "Colour palette: black, deep violet, electric blue, warm amber accents.\nTypography: clean, modern sans-serif, lowercase branding.\nCover art direction: nighttime cityscapes, neon reflections, minimal text.\nPhoto style: low-light, candid, film-grain.\nVideo style: handheld, intimate, warm/cool contrast lighting.\nMoodboard links: (add links here)\nDo: moody lighting, real moments. Don't: stock-photo energy, overly bright colors.",
        updatedAt: now,
      },
      {
        id: "brand-copy",
        section: "Copy Bank",
        title: "Copy Bank",
        content:
          "Short bio: 6am makes emotional house music for the hours when you're alone with your thoughts.\nLong bio: (write a longer version here)\nSong description template: \"[Song] is about [theme] — [one line emotional hook].\"\nPress blurb: (write press blurb here)\nCaption ideas: \"a small piece of [song] 🎹\", \"this one's for the people still healing\"\nOne-liners: \"emotional music to drive to at night\"\nPitch language: \"Emotional, piano-driven house for fans of [reference artists].\"",
        updatedAt: now,
      },
    ],
    weeklyReviews: [
      {
        id: "review-1",
        weekStartDate: "2026-06-01",
        creationNotes: "Finished the mix for June 26 and started a new piano idea.",
        contentNotes:
          "Posted the Midnight Drive piano version, it performed better than expected.",
        releaseNotes: "Locked the release date for June 26. Cover art still needs work.",
        growthNotes: "Gained ~120 followers on TikTok this week.",
        emotionalRealityNotes:
          "Spiraled a bit comparing my numbers to other artists. Felt proud of finishing the mix.",
        nextWeekReleasePriority: "Finalize cover art for June 26",
        nextWeekContentPriority: "Film the studio session teaser",
        nextWeekCreationPriority: "Finish the master for June 26",
        nextWeekBrandSkillPriority: "Write the long artist bio",
        createdAt: now,
        updatedAt: now,
      },
    ],
    tasks: [
      {
        id: "task-1",
        title: "Approve final master for June 26",
        area: "Release",
        linkedSongId: songIdJune,
        linkedReleaseId: "release-june-26",
        linkedContentId: null,
        dueDate: "2026-06-12",
        priority: "High",
        status: "In Progress",
        notes: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-2",
        title: "Film studio session teaser",
        area: "Content",
        linkedSongId: songIdJune,
        linkedReleaseId: null,
        linkedContentId: "content-2",
        dueDate: "2026-06-13",
        priority: "Medium",
        status: "Not Started",
        notes: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-3",
        title: "Write second verse for Resilience",
        area: "Creative",
        linkedSongId: "song-idea-2",
        linkedReleaseId: null,
        linkedContentId: null,
        dueDate: "2026-06-14",
        priority: "Low",
        status: "Not Started",
        notes: "",
        createdAt: now,
        updatedAt: now,
      },
    ],
    notToday: [
      { id: "nt-1", text: "Do not panic over TikTok views" },
      { id: "nt-2", text: "Do not redesign the whole brand today" },
      { id: "nt-3", text: "Do not start 5 new songs instead of finishing one" },
      { id: "nt-4", text: "Do not obsess over analytics outside review time" },
      { id: "nt-5", text: "Do not overthink the entire music career tonight" },
    ],
    todayPriority: "Approve the final master for June 26",
  };
}
