import { ChecklistItem, OSState } from "../types/os";

const now = new Date().toISOString();

export const RELEASE_CHECKLIST_LABELS = [
  "28 reel style hook videos",
  "Visual/music video",
  "Photoshoot",
  "Playlisting",
  "Playlist pitch",
  "YouTube video upload",
];

export function checklist(labels: string[], doneCount = 0): ChecklistItem[] {
  return labels.map((label, i) => ({
    id: `${label}-${i}`.replace(/\s+/g, "-"),
    label,
    done: i < doneCount,
  }));
}

export function buildReleaseChecklist(doneCount = 0): ChecklistItem[] {
  return checklist(RELEASE_CHECKLIST_LABELS, doneCount);
}

export function emptyChecklists() {
  return {
    preReleaseChecklist: buildReleaseChecklist(),
    releaseDayChecklist: [],
    postReleaseChecklist: [],
  };
}

export function buildSeedData(): OSState {
  const songIdJune = "song-june-26";
  const songIdReleased = "song-midnight-drive";
  const releaseIdJune = "release-june-26";

  return {
    songs: [
      {
        id: songIdJune,
        title: "June 26",
        stage: "Mastering",
        priority: "High",
        vibe: "uplifting, bittersweet",
        theme: "moving on while still caring",
        genre: "house / pop",
        bpm: "124",
        key: "A minor",
        collaborators: "Jay (vocals)",
        producer: "6am",
        nextAction: "Approve final master",
        releasePotential: "High",
        notes: "Lead single for the June 26 rollout.",
        fileLinks: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: songIdReleased,
        title: "Midnight Drive",
        stage: "Released",
        priority: "Medium",
        vibe: "nighttime, reflective",
        theme: "driving alone after a breakup",
        genre: "house",
        bpm: "122",
        key: "G minor",
        collaborators: "",
        producer: "6am",
        nextAction: "Repurpose clips for content",
        releasePotential: "Medium",
        notes: "Released last month, steady streams.",
        fileLinks: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-idea-1",
        title: "Untitled Piano Idea",
        stage: "Idea",
        priority: "Medium",
        vibe: "intimate, raw",
        theme: "early morning clarity",
        genre: "house / piano",
        bpm: "",
        key: "",
        collaborators: "",
        producer: "",
        nextAction: "Build out a full demo",
        releasePotential: "Medium",
        notes: "Voice memo from last week, has a good hook.",
        fileLinks: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-idea-2",
        title: "Resilience",
        stage: "Demo",
        priority: "Low",
        vibe: "anthemic, hopeful",
        theme: "ambition after failure",
        genre: "house / pop",
        bpm: "126",
        key: "C major",
        collaborators: "",
        producer: "6am",
        nextAction: "Write second verse",
        releasePotential: "Medium",
        notes: "",
        fileLinks: "",
        createdAt: now,
        updatedAt: now,
      },
    ],
    releases: [
      {
        id: releaseIdJune,
        title: "June 26 Release",
        linkedSongId: songIdJune,
        releaseDate: "2026-06-26",
        phase: "Pre-release",
        progress: 45,
        notes: "Lead single. Focus rollout for the next 2 weeks.",
        preReleaseChecklist: buildReleaseChecklist(1),
        releaseDayChecklist: [],
        postReleaseChecklist: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "release-midnight-drive",
        title: "Midnight Drive",
        linkedSongId: songIdReleased,
        releaseDate: "2026-05-10",
        phase: "Post-release",
        progress: 100,
        notes: "Already out. Repurposing content from this.",
        preReleaseChecklist: buildReleaseChecklist(RELEASE_CHECKLIST_LABELS.length),
        releaseDayChecklist: [],
        postReleaseChecklist: [],
        createdAt: now,
        updatedAt: now,
      },
    ],
    content: [
      {
        id: "content-1",
        title: "POV: you finally let go of someone",
        platform: "TikTok",
        linkedSongId: songIdJune,
        format: "lyric meaning",
        status: "Idea",
        caption: "POV: you finally let go of someone who never deserved your loyalty",
        filmingNotes: "Shoot at golden hour, simple direct-to-camera setup.",
        postDate: "",
        metrics: { views: 0, likes: 0, comments: 0, shares: 0, saves: 0 },
        learning: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "content-2",
        title: "Studio session teaser",
        platform: "Instagram",
        linkedSongId: songIdJune,
        format: "studio clip",
        status: "Scripted",
        caption: "a small piece of June 26 🎹",
        filmingNotes: "Capture hands on keys + headphones, moody lighting.",
        postDate: "",
        metrics: { views: 0, likes: 0, comments: 0, shares: 0, saves: 0 },
        learning: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "content-3",
        title: "Midnight Drive piano version",
        platform: "YouTube Shorts",
        linkedSongId: songIdReleased,
        format: "piano version",
        status: "Posted",
        caption: "stripped back version of Midnight Drive",
        filmingNotes: "",
        postDate: "2026-05-20",
        metrics: { views: 4200, likes: 380, comments: 22, shares: 14, saves: 60 },
        learning: "Stripped down versions seem to perform better than full mixes.",
        createdAt: now,
        updatedAt: now,
      },
    ],
    assets: [],
    vault: [
      {
        id: "vault-1",
        category: "Lyric idea",
        text: "\"I left the porch light on for someone who isn't coming back\"",
        mood: "bittersweet",
        linkedSongId: null,
        priority: "Medium",
        status: "Raw",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "vault-2",
        category: "Visual idea",
        text: "Cover art concept: empty highway at sunrise, neon reflections on wet road",
        mood: "nighttime / reflective",
        linkedSongId: songIdJune,
        priority: "High",
        status: "Useful",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "vault-3",
        category: "Rollout idea",
        text: "Countdown series: 5 days of behind-the-scenes clips before June 26 drops",
        mood: "energetic",
        linkedSongId: songIdJune,
        priority: "High",
        status: "Raw",
        createdAt: now,
        updatedAt: now,
      },
    ],
    brand: [],
    weeklyReviews: [],
    tasks: [
      {
        id: "task-1",
        title: "Approve final master for June 26",
        area: "Release",
        linkedSongId: songIdJune,
        linkedReleaseId: releaseIdJune,
        linkedContentId: null,
        dueDate: "2026-06-12",
        priority: "High",
        status: "In Progress",
        notes: "",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-2",
        title: "Film studio session teaser",
        area: "Content",
        linkedSongId: songIdJune,
        linkedReleaseId: null,
        linkedContentId: "content-2",
        dueDate: "2026-06-13",
        priority: "Medium",
        status: "Todo",
        notes: "",
        createdAt: now,
        updatedAt: now,
      },
    ],
    notToday: [],
    todayPriority: "",
    priorityItems: [],
    budgetItems: [],
  };
}
